//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 

namespace Common.Models.XML
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class CreateItemRequest
    {

        private CreateItemRequestItem itemField;

        /// <remarks/>
        public CreateItemRequestItem Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItem
    {

        private string sellerIDField;

        private string sellerPwdField;

        private string titleField;

        private string subtitleField;

        private string categoryField;

        private string iSBN10Field;

        private string iSBN13Field;

        private string eBayCategoryField;

        private string vShopCategoryField;

        private object optionalReference1Field;

        private object optionalReference2Field;

        private CreateItemRequestItemTags tagsField;

        private string startTimeField;

        private string durationField;

        private string startPriceField;

        private string bidIncrementField;

        private string buyNowPriceField;

        private string listAsClassifiedAdField;

        private string quantityField;

        private string brandNewField;

        private CreateItemRequestItemPromotionalFeatures promotionalFeaturesField;

        private CreateItemRequestItemAutoRelistFeatures autoRelistFeaturesField;

        private string suburbField;

        private string stateField;

        private string postcodeField;

        private CreateItemRequestItemPaymentMethods paymentMethodsField;

        private string paymentInstField;

        private CreateItemRequestItemPostage postageField;

        private string provideReturnRefundPolicyField;

        private CreateItemRequestItemPostToLocation postToLocationField;

        private string postInstField;

        private string descriptionField;

        private string pic1Field;

        private string pic2Field;

        private string pic3Field;

        private string pic4Field;

        private string pic5Field;

        private string pic6Field;

        private string pic7Field;

        private string pic8Field;

        private string pic9Field;

        private string pic10Field;

        private string pic11Field;

        private string gTINField;

        private string mPNField;

        private string brandField;

        /// <remarks/>
        public string SellerID
        {
            get
            {
                return this.sellerIDField;
            }
            set
            {
                this.sellerIDField = value;
            }
        }

        /// <remarks/>
        public string SellerPwd
        {
            get
            {
                return this.sellerPwdField;
            }
            set
            {
                this.sellerPwdField = value;
            }
        }

        /// <remarks/>
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        public string Subtitle
        {
            get
            {
                return this.subtitleField;
            }
            set
            {
                this.subtitleField = value;
            }
        }

        /// <remarks/>
        public string Category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        public string ISBN10
        {
            get
            {
                return this.iSBN10Field;
            }
            set
            {
                this.iSBN10Field = value;
            }
        }

        /// <remarks/>
        public string ISBN13
        {
            get
            {
                return this.iSBN13Field;
            }
            set
            {
                this.iSBN13Field = value;
            }
        }

        /// <remarks/>
        public string eBayCategory
        {
            get
            {
                return this.eBayCategoryField;
            }
            set
            {
                this.eBayCategoryField = value;
            }
        }

        /// <remarks/>
        public string vShopCategory
        {
            get
            {
                return this.vShopCategoryField;
            }
            set
            {
                this.vShopCategoryField = value;
            }
        }

        /// <remarks/>
        public object OptionalReference1
        {
            get
            {
                return this.optionalReference1Field;
            }
            set
            {
                this.optionalReference1Field = value;
            }
        }

        /// <remarks/>
        public object OptionalReference2
        {
            get
            {
                return this.optionalReference2Field;
            }
            set
            {
                this.optionalReference2Field = value;
            }
        }

        /// <remarks/>
        public CreateItemRequestItemTags Tags
        {
            get
            {
                return this.tagsField;
            }
            set
            {
                this.tagsField = value;
            }
        }

        /// <remarks/>
        public string StartTime
        {
            get
            {
                return this.startTimeField;
            }
            set
            {
                this.startTimeField = value;
            }
        }

        /// <remarks/>
        public string Duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }

        /// <remarks/>
        public string StartPrice
        {
            get
            {
                return this.startPriceField;
            }
            set
            {
                this.startPriceField = value;
            }
        }

        /// <remarks/>
        public string BidIncrement
        {
            get
            {
                return this.bidIncrementField;
            }
            set
            {
                this.bidIncrementField = value;
            }
        }

        /// <remarks/>
        public string BuyNowPrice
        {
            get
            {
                return this.buyNowPriceField;
            }
            set
            {
                this.buyNowPriceField = value;
            }
        }

        /// <remarks/>
        public string ListAsClassifiedAd
        {
            get
            {
                return this.listAsClassifiedAdField;
            }
            set
            {
                this.listAsClassifiedAdField = value;
            }
        }

        /// <remarks/>
        public string Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }

        /// <remarks/>
        public string BrandNew
        {
            get
            {
                return this.brandNewField;
            }
            set
            {
                this.brandNewField = value;
            }
        }

        /// <remarks/>
        public CreateItemRequestItemPromotionalFeatures PromotionalFeatures
        {
            get
            {
                return this.promotionalFeaturesField;
            }
            set
            {
                this.promotionalFeaturesField = value;
            }
        }

        /// <remarks/>
        public CreateItemRequestItemAutoRelistFeatures AutoRelistFeatures
        {
            get
            {
                return this.autoRelistFeaturesField;
            }
            set
            {
                this.autoRelistFeaturesField = value;
            }
        }

        /// <remarks/>
        public string Suburb
        {
            get
            {
                return this.suburbField;
            }
            set
            {
                this.suburbField = value;
            }
        }

        /// <remarks/>
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        public string Postcode
        {
            get
            {
                return this.postcodeField;
            }
            set
            {
                this.postcodeField = value;
            }
        }

        /// <remarks/>
        public CreateItemRequestItemPaymentMethods PaymentMethods
        {
            get
            {
                return this.paymentMethodsField;
            }
            set
            {
                this.paymentMethodsField = value;
            }
        }

        /// <remarks/>
        public string PaymentInst
        {
            get
            {
                return this.paymentInstField;
            }
            set
            {
                this.paymentInstField = value;
            }
        }

        /// <remarks/>
        public CreateItemRequestItemPostage Postage
        {
            get
            {
                return this.postageField;
            }
            set
            {
                this.postageField = value;
            }
        }

        /// <remarks/>
        public string ProvideReturnRefundPolicy
        {
            get
            {
                return this.provideReturnRefundPolicyField;
            }
            set
            {
                this.provideReturnRefundPolicyField = value;
            }
        }

        /// <remarks/>
        public CreateItemRequestItemPostToLocation PostToLocation
        {
            get
            {
                return this.postToLocationField;
            }
            set
            {
                this.postToLocationField = value;
            }
        }

        /// <remarks/>
        public string PostInst
        {
            get
            {
                return this.postInstField;
            }
            set
            {
                this.postInstField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string Pic1
        {
            get
            {
                return this.pic1Field;
            }
            set
            {
                this.pic1Field = value;
            }
        }

        /// <remarks/>
        public string Pic2
        {
            get
            {
                return this.pic2Field;
            }
            set
            {
                this.pic2Field = value;
            }
        }

        /// <remarks/>
        public string Pic3
        {
            get
            {
                return this.pic3Field;
            }
            set
            {
                this.pic3Field = value;
            }
        }

        /// <remarks/>
        public string Pic4
        {
            get
            {
                return this.pic4Field;
            }
            set
            {
                this.pic4Field = value;
            }
        }

        /// <remarks/>
        public string Pic5
        {
            get
            {
                return this.pic5Field;
            }
            set
            {
                this.pic5Field = value;
            }
        }

        /// <remarks/>
        public string Pic6
        {
            get
            {
                return this.pic6Field;
            }
            set
            {
                this.pic6Field = value;
            }
        }

        /// <remarks/>
        public string Pic7
        {
            get
            {
                return this.pic7Field;
            }
            set
            {
                this.pic7Field = value;
            }
        }

        /// <remarks/>
        public string Pic8
        {
            get
            {
                return this.pic8Field;
            }
            set
            {
                this.pic8Field = value;
            }
        }

        /// <remarks/>
        public string Pic9
        {
            get
            {
                return this.pic9Field;
            }
            set
            {
                this.pic9Field = value;
            }
        }

        /// <remarks/>
        public string Pic10
        {
            get
            {
                return this.pic10Field;
            }
            set
            {
                this.pic10Field = value;
            }
        }

        /// <remarks/>
        public string Pic11
        {
            get
            {
                return this.pic11Field;
            }
            set
            {
                this.pic11Field = value;
            }
        }

        /// <remarks/>
        public string GTIN
        {
            get
            {
                return this.gTINField;
            }
            set
            {
                this.gTINField = value;
            }
        }

        /// <remarks/>
        public string MPN
        {
            get
            {
                return this.mPNField;
            }
            set
            {
                this.mPNField = value;
            }
        }

        /// <remarks/>
        public string Brand
        {
            get
            {
                return this.brandField;
            }
            set
            {
                this.brandField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemTags
    {

        private CreateItemRequestItemTagsAttrSet attrSetField;

        /// <remarks/>
        public CreateItemRequestItemTagsAttrSet AttrSet
        {
            get
            {
                return this.attrSetField;
            }
            set
            {
                this.attrSetField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemTagsAttrSet
    {

        private CreateItemRequestItemTagsAttrSetAttr1 attr1Field;

        private CreateItemRequestItemTagsAttrSetAttr2 attr2Field;

        private CreateItemRequestItemTagsAttrSetAttr3 attr3Field;

        private CreateItemRequestItemTagsAttrSetAttr4 attr4Field;

        private CreateItemRequestItemTagsAttrSetAttr5 attr5Field;

        private CreateItemRequestItemTagsAttrSetAttr6 attr6Field;

        private CreateItemRequestItemTagsAttrSetAttr7 attr7Field;

        private CreateItemRequestItemTagsAttrSetAttr8 attr8Field;

        private CreateItemRequestItemTagsAttrSetAttr9 attr9Field;

        private CreateItemRequestItemTagsAttrSetAttr10 attr10Field;

        private string attrSetNameField;

        private string attrSetIDField;

        /// <remarks/>
        public CreateItemRequestItemTagsAttrSetAttr1 Attr1
        {
            get
            {
                return this.attr1Field;
            }
            set
            {
                this.attr1Field = value;
            }
        }

        /// <remarks/>
        public CreateItemRequestItemTagsAttrSetAttr2 Attr2
        {
            get
            {
                return this.attr2Field;
            }
            set
            {
                this.attr2Field = value;
            }
        }

        /// <remarks/>
        public CreateItemRequestItemTagsAttrSetAttr3 Attr3
        {
            get
            {
                return this.attr3Field;
            }
            set
            {
                this.attr3Field = value;
            }
        }

        /// <remarks/>
        public CreateItemRequestItemTagsAttrSetAttr4 Attr4
        {
            get
            {
                return this.attr4Field;
            }
            set
            {
                this.attr4Field = value;
            }
        }

        /// <remarks/>
        public CreateItemRequestItemTagsAttrSetAttr5 Attr5
        {
            get
            {
                return this.attr5Field;
            }
            set
            {
                this.attr5Field = value;
            }
        }

        /// <remarks/>
        public CreateItemRequestItemTagsAttrSetAttr6 Attr6
        {
            get
            {
                return this.attr6Field;
            }
            set
            {
                this.attr6Field = value;
            }
        }

        /// <remarks/>
        public CreateItemRequestItemTagsAttrSetAttr7 Attr7
        {
            get
            {
                return this.attr7Field;
            }
            set
            {
                this.attr7Field = value;
            }
        }

        /// <remarks/>
        public CreateItemRequestItemTagsAttrSetAttr8 Attr8
        {
            get
            {
                return this.attr8Field;
            }
            set
            {
                this.attr8Field = value;
            }
        }

        /// <remarks/>
        public CreateItemRequestItemTagsAttrSetAttr9 Attr9
        {
            get
            {
                return this.attr9Field;
            }
            set
            {
                this.attr9Field = value;
            }
        }

        /// <remarks/>
        public CreateItemRequestItemTagsAttrSetAttr10 Attr10
        {
            get
            {
                return this.attr10Field;
            }
            set
            {
                this.attr10Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttrSetName
        {
            get
            {
                return this.attrSetNameField;
            }
            set
            {
                this.attrSetNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttrSetID
        {
            get
            {
                return this.attrSetIDField;
            }
            set
            {
                this.attrSetIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemTagsAttrSetAttr1
    {

        private CreateItemRequestItemTagsAttrSetAttr1SelectedValue selectedValueField;

        private string attrNameField;

        private string attrIDField;

        /// <remarks/>
        public CreateItemRequestItemTagsAttrSetAttr1SelectedValue SelectedValue
        {
            get
            {
                return this.selectedValueField;
            }
            set
            {
                this.selectedValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttrName
        {
            get
            {
                return this.attrNameField;
            }
            set
            {
                this.attrNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttrID
        {
            get
            {
                return this.attrIDField;
            }
            set
            {
                this.attrIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemTagsAttrSetAttr1SelectedValue
    {

        private string valueNameField;

        private string valueIDField;

        private string otherValueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ValueName
        {
            get
            {
                return this.valueNameField;
            }
            set
            {
                this.valueNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ValueID
        {
            get
            {
                return this.valueIDField;
            }
            set
            {
                this.valueIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OtherValue
        {
            get
            {
                return this.otherValueField;
            }
            set
            {
                this.otherValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemTagsAttrSetAttr2
    {

        private CreateItemRequestItemTagsAttrSetAttr2SelectedValue selectedValueField;

        private string attrNameField;

        private string attrIDField;

        /// <remarks/>
        public CreateItemRequestItemTagsAttrSetAttr2SelectedValue SelectedValue
        {
            get
            {
                return this.selectedValueField;
            }
            set
            {
                this.selectedValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttrName
        {
            get
            {
                return this.attrNameField;
            }
            set
            {
                this.attrNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttrID
        {
            get
            {
                return this.attrIDField;
            }
            set
            {
                this.attrIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemTagsAttrSetAttr2SelectedValue
    {

        private string valueNameField;

        private string valueIDField;

        private string otherValueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ValueName
        {
            get
            {
                return this.valueNameField;
            }
            set
            {
                this.valueNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ValueID
        {
            get
            {
                return this.valueIDField;
            }
            set
            {
                this.valueIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OtherValue
        {
            get
            {
                return this.otherValueField;
            }
            set
            {
                this.otherValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemTagsAttrSetAttr3
    {

        private CreateItemRequestItemTagsAttrSetAttr3SelectedValue selectedValueField;

        private string attrNameField;

        private string attrIDField;

        /// <remarks/>
        public CreateItemRequestItemTagsAttrSetAttr3SelectedValue SelectedValue
        {
            get
            {
                return this.selectedValueField;
            }
            set
            {
                this.selectedValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttrName
        {
            get
            {
                return this.attrNameField;
            }
            set
            {
                this.attrNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttrID
        {
            get
            {
                return this.attrIDField;
            }
            set
            {
                this.attrIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemTagsAttrSetAttr3SelectedValue
    {

        private string valueNameField;

        private string valueIDField;

        private string otherValueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ValueName
        {
            get
            {
                return this.valueNameField;
            }
            set
            {
                this.valueNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ValueID
        {
            get
            {
                return this.valueIDField;
            }
            set
            {
                this.valueIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OtherValue
        {
            get
            {
                return this.otherValueField;
            }
            set
            {
                this.otherValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemTagsAttrSetAttr4
    {

        private CreateItemRequestItemTagsAttrSetAttr4SelectedValue selectedValueField;

        private string attrNameField;

        private string attrIDField;

        /// <remarks/>
        public CreateItemRequestItemTagsAttrSetAttr4SelectedValue SelectedValue
        {
            get
            {
                return this.selectedValueField;
            }
            set
            {
                this.selectedValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttrName
        {
            get
            {
                return this.attrNameField;
            }
            set
            {
                this.attrNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttrID
        {
            get
            {
                return this.attrIDField;
            }
            set
            {
                this.attrIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemTagsAttrSetAttr4SelectedValue
    {

        private string valueNameField;

        private string valueIDField;

        private string otherValueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ValueName
        {
            get
            {
                return this.valueNameField;
            }
            set
            {
                this.valueNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ValueID
        {
            get
            {
                return this.valueIDField;
            }
            set
            {
                this.valueIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OtherValue
        {
            get
            {
                return this.otherValueField;
            }
            set
            {
                this.otherValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemTagsAttrSetAttr5
    {

        private CreateItemRequestItemTagsAttrSetAttr5SelectedValue selectedValueField;

        private string attrNameField;

        private string attrIDField;

        /// <remarks/>
        public CreateItemRequestItemTagsAttrSetAttr5SelectedValue SelectedValue
        {
            get
            {
                return this.selectedValueField;
            }
            set
            {
                this.selectedValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttrName
        {
            get
            {
                return this.attrNameField;
            }
            set
            {
                this.attrNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttrID
        {
            get
            {
                return this.attrIDField;
            }
            set
            {
                this.attrIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemTagsAttrSetAttr5SelectedValue
    {

        private string valueNameField;

        private string valueIDField;

        private string otherValueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ValueName
        {
            get
            {
                return this.valueNameField;
            }
            set
            {
                this.valueNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ValueID
        {
            get
            {
                return this.valueIDField;
            }
            set
            {
                this.valueIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OtherValue
        {
            get
            {
                return this.otherValueField;
            }
            set
            {
                this.otherValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemTagsAttrSetAttr6
    {

        private CreateItemRequestItemTagsAttrSetAttr6SelectedValue selectedValueField;

        private string attrNameField;

        private string attrIDField;

        /// <remarks/>
        public CreateItemRequestItemTagsAttrSetAttr6SelectedValue SelectedValue
        {
            get
            {
                return this.selectedValueField;
            }
            set
            {
                this.selectedValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttrName
        {
            get
            {
                return this.attrNameField;
            }
            set
            {
                this.attrNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttrID
        {
            get
            {
                return this.attrIDField;
            }
            set
            {
                this.attrIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemTagsAttrSetAttr6SelectedValue
    {

        private string valueNameField;

        private string valueIDField;

        private string otherValueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ValueName
        {
            get
            {
                return this.valueNameField;
            }
            set
            {
                this.valueNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ValueID
        {
            get
            {
                return this.valueIDField;
            }
            set
            {
                this.valueIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OtherValue
        {
            get
            {
                return this.otherValueField;
            }
            set
            {
                this.otherValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemTagsAttrSetAttr7
    {

        private CreateItemRequestItemTagsAttrSetAttr7SelectedValue selectedValueField;

        private string attrNameField;

        private string attrIDField;

        /// <remarks/>
        public CreateItemRequestItemTagsAttrSetAttr7SelectedValue SelectedValue
        {
            get
            {
                return this.selectedValueField;
            }
            set
            {
                this.selectedValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttrName
        {
            get
            {
                return this.attrNameField;
            }
            set
            {
                this.attrNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttrID
        {
            get
            {
                return this.attrIDField;
            }
            set
            {
                this.attrIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemTagsAttrSetAttr7SelectedValue
    {

        private string valueNameField;

        private string valueIDField;

        private string otherValueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ValueName
        {
            get
            {
                return this.valueNameField;
            }
            set
            {
                this.valueNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ValueID
        {
            get
            {
                return this.valueIDField;
            }
            set
            {
                this.valueIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OtherValue
        {
            get
            {
                return this.otherValueField;
            }
            set
            {
                this.otherValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemTagsAttrSetAttr8
    {

        private CreateItemRequestItemTagsAttrSetAttr8SelectedValue selectedValueField;

        private string attrNameField;

        private string attrIDField;

        /// <remarks/>
        public CreateItemRequestItemTagsAttrSetAttr8SelectedValue SelectedValue
        {
            get
            {
                return this.selectedValueField;
            }
            set
            {
                this.selectedValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttrName
        {
            get
            {
                return this.attrNameField;
            }
            set
            {
                this.attrNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttrID
        {
            get
            {
                return this.attrIDField;
            }
            set
            {
                this.attrIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemTagsAttrSetAttr8SelectedValue
    {

        private string valueNameField;

        private string valueIDField;

        private string otherValueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ValueName
        {
            get
            {
                return this.valueNameField;
            }
            set
            {
                this.valueNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ValueID
        {
            get
            {
                return this.valueIDField;
            }
            set
            {
                this.valueIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OtherValue
        {
            get
            {
                return this.otherValueField;
            }
            set
            {
                this.otherValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemTagsAttrSetAttr9
    {

        private CreateItemRequestItemTagsAttrSetAttr9SelectedValue selectedValueField;

        private string attrNameField;

        private string attrIDField;

        /// <remarks/>
        public CreateItemRequestItemTagsAttrSetAttr9SelectedValue SelectedValue
        {
            get
            {
                return this.selectedValueField;
            }
            set
            {
                this.selectedValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttrName
        {
            get
            {
                return this.attrNameField;
            }
            set
            {
                this.attrNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttrID
        {
            get
            {
                return this.attrIDField;
            }
            set
            {
                this.attrIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemTagsAttrSetAttr9SelectedValue
    {

        private string valueNameField;

        private string valueIDField;

        private string otherValueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ValueName
        {
            get
            {
                return this.valueNameField;
            }
            set
            {
                this.valueNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ValueID
        {
            get
            {
                return this.valueIDField;
            }
            set
            {
                this.valueIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OtherValue
        {
            get
            {
                return this.otherValueField;
            }
            set
            {
                this.otherValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemTagsAttrSetAttr10
    {

        private CreateItemRequestItemTagsAttrSetAttr10SelectedValue selectedValueField;

        private string attrNameField;

        private string attrIDField;

        /// <remarks/>
        public CreateItemRequestItemTagsAttrSetAttr10SelectedValue SelectedValue
        {
            get
            {
                return this.selectedValueField;
            }
            set
            {
                this.selectedValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttrName
        {
            get
            {
                return this.attrNameField;
            }
            set
            {
                this.attrNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttrID
        {
            get
            {
                return this.attrIDField;
            }
            set
            {
                this.attrIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemTagsAttrSetAttr10SelectedValue
    {

        private string valueNameField;

        private string valueIDField;

        private string otherValueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ValueName
        {
            get
            {
                return this.valueNameField;
            }
            set
            {
                this.valueNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ValueID
        {
            get
            {
                return this.valueIDField;
            }
            set
            {
                this.valueIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OtherValue
        {
            get
            {
                return this.otherValueField;
            }
            set
            {
                this.otherValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemPromotionalFeatures
    {

        private string highlightListingField;

        private string frontpageField;

        private string categorySpecialField;

        private string boldField;

        private string bidNowField;

        private string auto1MinuteField;

        /// <remarks/>
        public string HighlightListing
        {
            get
            {
                return this.highlightListingField;
            }
            set
            {
                this.highlightListingField = value;
            }
        }

        /// <remarks/>
        public string Frontpage
        {
            get
            {
                return this.frontpageField;
            }
            set
            {
                this.frontpageField = value;
            }
        }

        /// <remarks/>
        public string CategorySpecial
        {
            get
            {
                return this.categorySpecialField;
            }
            set
            {
                this.categorySpecialField = value;
            }
        }

        /// <remarks/>
        public string Bold
        {
            get
            {
                return this.boldField;
            }
            set
            {
                this.boldField = value;
            }
        }

        /// <remarks/>
        public string BidNow
        {
            get
            {
                return this.bidNowField;
            }
            set
            {
                this.bidNowField = value;
            }
        }

        /// <remarks/>
        public string Auto1Minute
        {
            get
            {
                return this.auto1MinuteField;
            }
            set
            {
                this.auto1MinuteField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemAutoRelistFeatures
    {

        private string autoRelistTypeField;

        /// <remarks/>
        public string AutoRelistType
        {
            get
            {
                return this.autoRelistTypeField;
            }
            set
            {
                this.autoRelistTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemPaymentMethods
    {

        private string bankChequeField;

        private string bankDepositField;

        private string cashField;

        private string cODField;

        private string creditCardField;

        private string escrowField;

        private string moneyOrderField;

        private string paymateField;

        private string payPalField;

        private string personalChequeField;

        private string otherField;

        private string provideBankDetailsToBuyerField;

        /// <remarks/>
        public string BankCheque
        {
            get
            {
                return this.bankChequeField;
            }
            set
            {
                this.bankChequeField = value;
            }
        }

        /// <remarks/>
        public string BankDeposit
        {
            get
            {
                return this.bankDepositField;
            }
            set
            {
                this.bankDepositField = value;
            }
        }

        /// <remarks/>
        public string Cash
        {
            get
            {
                return this.cashField;
            }
            set
            {
                this.cashField = value;
            }
        }

        /// <remarks/>
        public string COD
        {
            get
            {
                return this.cODField;
            }
            set
            {
                this.cODField = value;
            }
        }

        /// <remarks/>
        public string CreditCard
        {
            get
            {
                return this.creditCardField;
            }
            set
            {
                this.creditCardField = value;
            }
        }

        /// <remarks/>
        public string Escrow
        {
            get
            {
                return this.escrowField;
            }
            set
            {
                this.escrowField = value;
            }
        }

        /// <remarks/>
        public string MoneyOrder
        {
            get
            {
                return this.moneyOrderField;
            }
            set
            {
                this.moneyOrderField = value;
            }
        }

        /// <remarks/>
        public string Paymate
        {
            get
            {
                return this.paymateField;
            }
            set
            {
                this.paymateField = value;
            }
        }

        /// <remarks/>
        public string PayPal
        {
            get
            {
                return this.payPalField;
            }
            set
            {
                this.payPalField = value;
            }
        }

        /// <remarks/>
        public string PersonalCheque
        {
            get
            {
                return this.personalChequeField;
            }
            set
            {
                this.personalChequeField = value;
            }
        }

        /// <remarks/>
        public string Other
        {
            get
            {
                return this.otherField;
            }
            set
            {
                this.otherField = value;
            }
        }

        /// <remarks/>
        public string ProvideBankDetailsToBuyer
        {
            get
            {
                return this.provideBankDetailsToBuyerField;
            }
            set
            {
                this.provideBankDetailsToBuyerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemPostage
    {

        private string typeField;

        private string fixedPostageField;

        private CreateItemRequestItemPostageFixedPostageByLocation fixedPostageByLocationField;

        private CreateItemRequestItemPostageCalculatedPostage calculatedPostageField;

        private CreateItemRequestItemPostageTemando temandoField;

        /// <remarks/>
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public string FixedPostage
        {
            get
            {
                return this.fixedPostageField;
            }
            set
            {
                this.fixedPostageField = value;
            }
        }

        /// <remarks/>
        public CreateItemRequestItemPostageFixedPostageByLocation FixedPostageByLocation
        {
            get
            {
                return this.fixedPostageByLocationField;
            }
            set
            {
                this.fixedPostageByLocationField = value;
            }
        }

        /// <remarks/>
        public CreateItemRequestItemPostageCalculatedPostage CalculatedPostage
        {
            get
            {
                return this.calculatedPostageField;
            }
            set
            {
                this.calculatedPostageField = value;
            }
        }

        /// <remarks/>
        public CreateItemRequestItemPostageTemando Temando
        {
            get
            {
                return this.temandoField;
            }
            set
            {
                this.temandoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemPostageFixedPostageByLocation
    {

        private string nSWField;

        private string vICField;

        private string qLDField;

        private string aCTField;

        private string ntField;

        private string tASField;

        private string saField;

        private string waField;

        /// <remarks/>
        public string NSW
        {
            get
            {
                return this.nSWField;
            }
            set
            {
                this.nSWField = value;
            }
        }

        /// <remarks/>
        public string VIC
        {
            get
            {
                return this.vICField;
            }
            set
            {
                this.vICField = value;
            }
        }

        /// <remarks/>
        public string QLD
        {
            get
            {
                return this.qLDField;
            }
            set
            {
                this.qLDField = value;
            }
        }

        /// <remarks/>
        public string ACT
        {
            get
            {
                return this.aCTField;
            }
            set
            {
                this.aCTField = value;
            }
        }

        /// <remarks/>
        public string NT
        {
            get
            {
                return this.ntField;
            }
            set
            {
                this.ntField = value;
            }
        }

        /// <remarks/>
        public string TAS
        {
            get
            {
                return this.tASField;
            }
            set
            {
                this.tASField = value;
            }
        }

        /// <remarks/>
        public string SA
        {
            get
            {
                return this.saField;
            }
            set
            {
                this.saField = value;
            }
        }

        /// <remarks/>
        public string WA
        {
            get
            {
                return this.waField;
            }
            set
            {
                this.waField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemPostageCalculatedPostage
    {

        private CreateItemRequestItemPostageCalculatedPostageDimensions dimensionsField;

        private string offerAPRegularField;

        private string offerAPExpressField;

        /// <remarks/>
        public CreateItemRequestItemPostageCalculatedPostageDimensions Dimensions
        {
            get
            {
                return this.dimensionsField;
            }
            set
            {
                this.dimensionsField = value;
            }
        }

        /// <remarks/>
        public string OfferAPRegular
        {
            get
            {
                return this.offerAPRegularField;
            }
            set
            {
                this.offerAPRegularField = value;
            }
        }

        /// <remarks/>
        public string OfferAPExpress
        {
            get
            {
                return this.offerAPExpressField;
            }
            set
            {
                this.offerAPExpressField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemPostageCalculatedPostageDimensions
    {

        private string lengthField;

        private string widthField;

        private string heightField;

        private string weightField;

        /// <remarks/>
        public string Length
        {
            get
            {
                return this.lengthField;
            }
            set
            {
                this.lengthField = value;
            }
        }

        /// <remarks/>
        public string Width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }

        /// <remarks/>
        public string Height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }

        /// <remarks/>
        public string Weight
        {
            get
            {
                return this.weightField;
            }
            set
            {
                this.weightField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemPostageTemando
    {

        private string pkgTypeField;

        private string weightField;

        private string lengthField;

        private string widthField;

        private string heightField;

        /// <remarks/>
        public string PkgType
        {
            get
            {
                return this.pkgTypeField;
            }
            set
            {
                this.pkgTypeField = value;
            }
        }

        /// <remarks/>
        public string Weight
        {
            get
            {
                return this.weightField;
            }
            set
            {
                this.weightField = value;
            }
        }

        /// <remarks/>
        public string Length
        {
            get
            {
                return this.lengthField;
            }
            set
            {
                this.lengthField = value;
            }
        }

        /// <remarks/>
        public string Width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }

        /// <remarks/>
        public string Height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class CreateItemRequestItemPostToLocation
    {

        private string worldwideField;

        private string nationalField;

        private string statewideField;

        private string localPickupField;

        /// <remarks/>
        public string Worldwide
        {
            get
            {
                return this.worldwideField;
            }
            set
            {
                this.worldwideField = value;
            }
        }

        /// <remarks/>
        public string National
        {
            get
            {
                return this.nationalField;
            }
            set
            {
                this.nationalField = value;
            }
        }

        /// <remarks/>
        public string Statewide
        {
            get
            {
                return this.statewideField;
            }
            set
            {
                this.statewideField = value;
            }
        }

        /// <remarks/>
        public string LocalPickup
        {
            get
            {
                return this.localPickupField;
            }
            set
            {
                this.localPickupField = value;
            }
        }
    }

}