//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GetCategoryResponse {
    
    private string timeStampField;
    
    private string versionField;
    
    private GetCategoryResponseCategory[] categoryArrayField;
    
    /// <remarks/>
    public string TimeStamp {
        get {
            return this.timeStampField;
        }
        set {
            this.timeStampField = value;
        }
    }
    
    /// <remarks/>
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Category", IsNullable=false)]
    public GetCategoryResponseCategory[] CategoryArray {
        get {
            return this.categoryArrayField;
        }
        set {
            this.categoryArrayField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class GetCategoryResponseCategory {
    
    private string categoryNumField;
    
    private string categoryLevelField;
    
    private string categoryNameField;
    
    private string categoryParentNumField;
    
    private string leafCategoryField;
    
    private string isClassifiedCatField;
    
    /// <remarks/>
    public string CategoryNum {
        get {
            return this.categoryNumField;
        }
        set {
            this.categoryNumField = value;
        }
    }
    
    /// <remarks/>
    public string CategoryLevel {
        get {
            return this.categoryLevelField;
        }
        set {
            this.categoryLevelField = value;
        }
    }
    
    /// <remarks/>
    public string CategoryName {
        get {
            return this.categoryNameField;
        }
        set {
            this.categoryNameField = value;
        }
    }
    
    /// <remarks/>
    public string CategoryParentNum {
        get {
            return this.categoryParentNumField;
        }
        set {
            this.categoryParentNumField = value;
        }
    }
    
    /// <remarks/>
    public string LeafCategory {
        get {
            return this.leafCategoryField;
        }
        set {
            this.leafCategoryField = value;
        }
    }
    
    /// <remarks/>
    public string IsClassifiedCat {
        get {
            return this.isClassifiedCatField;
        }
        set {
            this.isClassifiedCatField = value;
        }
    }
}
