//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ReviseItemRequest {
    
    private ReviseItemRequestItem itemField;
    
    private string deleteFieldField;
    
    private string endItemField;
    
    private string relistItemField;
    
    /// <remarks/>
    public ReviseItemRequestItem Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    public string DeleteField {
        get {
            return this.deleteFieldField;
        }
        set {
            this.deleteFieldField = value;
        }
    }
    
    /// <remarks/>
    public string EndItem {
        get {
            return this.endItemField;
        }
        set {
            this.endItemField = value;
        }
    }
    
    /// <remarks/>
    public string RelistItem {
        get {
            return this.relistItemField;
        }
        set {
            this.relistItemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItem {
    
    private string sellerIDField;
    
    private string sellerPwdField;
    
    private string listingIDField;
    
    private string titleField;
    
    private string subtitleField;
    
    private string categoryField;
    
    private string iSBN10Field;
    
    private string iSBN13Field;
    
    private string vShopCategoryField;
    
    private object optionalReference1Field;
    
    private object optionalReference2Field;
    
    private ReviseItemRequestItemTags tagsField;
    
    private string durationField;
    
    private string startPriceField;
    
    private string bidIncrementField;
    
    private string buyNowPriceField;
    
    private string listAsClassifiedAdField;
    
    private string quantityField;
    
    private string brandNewField;
    
    private ReviseItemRequestItemPromotionalFeatures promotionalFeaturesField;
    
    private ReviseItemRequestItemAutoRelistFeatures autoRelistFeaturesField;
    
    private ReviseItemRequestItemPaymentMethods paymentMethodsField;
    
    private string paymentInstField;
    
    private ReviseItemRequestItemPostage postageField;
    
    private string provideReturnRefundPolicyField;
    
    private ReviseItemRequestItemPostToLocation postToLocationField;
    
    private string postInstField;
    
    private string descriptionField;
    
    private string pic1Field;
    
    private string pic2Field;
    
    private string pic3Field;
    
    /// <remarks/>
    public string SellerID {
        get {
            return this.sellerIDField;
        }
        set {
            this.sellerIDField = value;
        }
    }
    
    /// <remarks/>
    public string SellerPwd {
        get {
            return this.sellerPwdField;
        }
        set {
            this.sellerPwdField = value;
        }
    }
    
    /// <remarks/>
    public string ListingID {
        get {
            return this.listingIDField;
        }
        set {
            this.listingIDField = value;
        }
    }
    
    /// <remarks/>
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string Subtitle {
        get {
            return this.subtitleField;
        }
        set {
            this.subtitleField = value;
        }
    }
    
    /// <remarks/>
    public string Category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    public string ISBN10 {
        get {
            return this.iSBN10Field;
        }
        set {
            this.iSBN10Field = value;
        }
    }
    
    /// <remarks/>
    public string ISBN13 {
        get {
            return this.iSBN13Field;
        }
        set {
            this.iSBN13Field = value;
        }
    }
    
    /// <remarks/>
    public string vShopCategory {
        get {
            return this.vShopCategoryField;
        }
        set {
            this.vShopCategoryField = value;
        }
    }
    
    /// <remarks/>
    public object OptionalReference1 {
        get {
            return this.optionalReference1Field;
        }
        set {
            this.optionalReference1Field = value;
        }
    }
    
    /// <remarks/>
    public object OptionalReference2 {
        get {
            return this.optionalReference2Field;
        }
        set {
            this.optionalReference2Field = value;
        }
    }
    
    /// <remarks/>
    public ReviseItemRequestItemTags Tags {
        get {
            return this.tagsField;
        }
        set {
            this.tagsField = value;
        }
    }
    
    /// <remarks/>
    public string Duration {
        get {
            return this.durationField;
        }
        set {
            this.durationField = value;
        }
    }
    
    /// <remarks/>
    public string StartPrice {
        get {
            return this.startPriceField;
        }
        set {
            this.startPriceField = value;
        }
    }
    
    /// <remarks/>
    public string BidIncrement {
        get {
            return this.bidIncrementField;
        }
        set {
            this.bidIncrementField = value;
        }
    }
    
    /// <remarks/>
    public string BuyNowPrice {
        get {
            return this.buyNowPriceField;
        }
        set {
            this.buyNowPriceField = value;
        }
    }
    
    /// <remarks/>
    public string ListAsClassifiedAd {
        get {
            return this.listAsClassifiedAdField;
        }
        set {
            this.listAsClassifiedAdField = value;
        }
    }
    
    /// <remarks/>
    public string Quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
    
    /// <remarks/>
    public string BrandNew {
        get {
            return this.brandNewField;
        }
        set {
            this.brandNewField = value;
        }
    }
    
    /// <remarks/>
    public ReviseItemRequestItemPromotionalFeatures PromotionalFeatures {
        get {
            return this.promotionalFeaturesField;
        }
        set {
            this.promotionalFeaturesField = value;
        }
    }
    
    /// <remarks/>
    public ReviseItemRequestItemAutoRelistFeatures AutoRelistFeatures {
        get {
            return this.autoRelistFeaturesField;
        }
        set {
            this.autoRelistFeaturesField = value;
        }
    }
    
    /// <remarks/>
    public ReviseItemRequestItemPaymentMethods PaymentMethods {
        get {
            return this.paymentMethodsField;
        }
        set {
            this.paymentMethodsField = value;
        }
    }
    
    /// <remarks/>
    public string PaymentInst {
        get {
            return this.paymentInstField;
        }
        set {
            this.paymentInstField = value;
        }
    }
    
    /// <remarks/>
    public ReviseItemRequestItemPostage Postage {
        get {
            return this.postageField;
        }
        set {
            this.postageField = value;
        }
    }
    
    /// <remarks/>
    public string ProvideReturnRefundPolicy {
        get {
            return this.provideReturnRefundPolicyField;
        }
        set {
            this.provideReturnRefundPolicyField = value;
        }
    }
    
    /// <remarks/>
    public ReviseItemRequestItemPostToLocation PostToLocation {
        get {
            return this.postToLocationField;
        }
        set {
            this.postToLocationField = value;
        }
    }
    
    /// <remarks/>
    public string PostInst {
        get {
            return this.postInstField;
        }
        set {
            this.postInstField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string Pic1 {
        get {
            return this.pic1Field;
        }
        set {
            this.pic1Field = value;
        }
    }
    
    /// <remarks/>
    public string Pic2 {
        get {
            return this.pic2Field;
        }
        set {
            this.pic2Field = value;
        }
    }
    
    /// <remarks/>
    public string Pic3 {
        get {
            return this.pic3Field;
        }
        set {
            this.pic3Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemTags {
    
    private ReviseItemRequestItemTagsAttrSet attrSetField;
    
    /// <remarks/>
    public ReviseItemRequestItemTagsAttrSet AttrSet {
        get {
            return this.attrSetField;
        }
        set {
            this.attrSetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemTagsAttrSet {
    
    private ReviseItemRequestItemTagsAttrSetAttr1 attr1Field;
    
    private ReviseItemRequestItemTagsAttrSetAttr2 attr2Field;
    
    private ReviseItemRequestItemTagsAttrSetAttr3 attr3Field;
    
    private ReviseItemRequestItemTagsAttrSetAttr4 attr4Field;
    
    private ReviseItemRequestItemTagsAttrSetAttr5 attr5Field;
    
    private ReviseItemRequestItemTagsAttrSetAttr6 attr6Field;
    
    private ReviseItemRequestItemTagsAttrSetAttr7 attr7Field;
    
    private ReviseItemRequestItemTagsAttrSetAttr8 attr8Field;
    
    private ReviseItemRequestItemTagsAttrSetAttr9 attr9Field;
    
    private ReviseItemRequestItemTagsAttrSetAttr10 attr10Field;
    
    private string attrSetNameField;
    
    private string attrSetIDField;
    
    /// <remarks/>
    public ReviseItemRequestItemTagsAttrSetAttr1 Attr1 {
        get {
            return this.attr1Field;
        }
        set {
            this.attr1Field = value;
        }
    }
    
    /// <remarks/>
    public ReviseItemRequestItemTagsAttrSetAttr2 Attr2 {
        get {
            return this.attr2Field;
        }
        set {
            this.attr2Field = value;
        }
    }
    
    /// <remarks/>
    public ReviseItemRequestItemTagsAttrSetAttr3 Attr3 {
        get {
            return this.attr3Field;
        }
        set {
            this.attr3Field = value;
        }
    }
    
    /// <remarks/>
    public ReviseItemRequestItemTagsAttrSetAttr4 Attr4 {
        get {
            return this.attr4Field;
        }
        set {
            this.attr4Field = value;
        }
    }
    
    /// <remarks/>
    public ReviseItemRequestItemTagsAttrSetAttr5 Attr5 {
        get {
            return this.attr5Field;
        }
        set {
            this.attr5Field = value;
        }
    }
    
    /// <remarks/>
    public ReviseItemRequestItemTagsAttrSetAttr6 Attr6 {
        get {
            return this.attr6Field;
        }
        set {
            this.attr6Field = value;
        }
    }
    
    /// <remarks/>
    public ReviseItemRequestItemTagsAttrSetAttr7 Attr7 {
        get {
            return this.attr7Field;
        }
        set {
            this.attr7Field = value;
        }
    }
    
    /// <remarks/>
    public ReviseItemRequestItemTagsAttrSetAttr8 Attr8 {
        get {
            return this.attr8Field;
        }
        set {
            this.attr8Field = value;
        }
    }
    
    /// <remarks/>
    public ReviseItemRequestItemTagsAttrSetAttr9 Attr9 {
        get {
            return this.attr9Field;
        }
        set {
            this.attr9Field = value;
        }
    }
    
    /// <remarks/>
    public ReviseItemRequestItemTagsAttrSetAttr10 Attr10 {
        get {
            return this.attr10Field;
        }
        set {
            this.attr10Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AttrSetName {
        get {
            return this.attrSetNameField;
        }
        set {
            this.attrSetNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AttrSetID {
        get {
            return this.attrSetIDField;
        }
        set {
            this.attrSetIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemTagsAttrSetAttr1 {
    
    private ReviseItemRequestItemTagsAttrSetAttr1SelectedValue selectedValueField;
    
    private string attrNameField;
    
    private string attrIDField;
    
    /// <remarks/>
    public ReviseItemRequestItemTagsAttrSetAttr1SelectedValue SelectedValue {
        get {
            return this.selectedValueField;
        }
        set {
            this.selectedValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AttrName {
        get {
            return this.attrNameField;
        }
        set {
            this.attrNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AttrID {
        get {
            return this.attrIDField;
        }
        set {
            this.attrIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemTagsAttrSetAttr1SelectedValue {
    
    private string valueNameField;
    
    private string valueIDField;
    
    private string otherValueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ValueName {
        get {
            return this.valueNameField;
        }
        set {
            this.valueNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ValueID {
        get {
            return this.valueIDField;
        }
        set {
            this.valueIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OtherValue {
        get {
            return this.otherValueField;
        }
        set {
            this.otherValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemTagsAttrSetAttr2 {
    
    private ReviseItemRequestItemTagsAttrSetAttr2SelectedValue selectedValueField;
    
    private string attrNameField;
    
    private string attrIDField;
    
    /// <remarks/>
    public ReviseItemRequestItemTagsAttrSetAttr2SelectedValue SelectedValue {
        get {
            return this.selectedValueField;
        }
        set {
            this.selectedValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AttrName {
        get {
            return this.attrNameField;
        }
        set {
            this.attrNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AttrID {
        get {
            return this.attrIDField;
        }
        set {
            this.attrIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemTagsAttrSetAttr2SelectedValue {
    
    private string valueNameField;
    
    private string valueIDField;
    
    private string otherValueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ValueName {
        get {
            return this.valueNameField;
        }
        set {
            this.valueNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ValueID {
        get {
            return this.valueIDField;
        }
        set {
            this.valueIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OtherValue {
        get {
            return this.otherValueField;
        }
        set {
            this.otherValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemTagsAttrSetAttr3 {
    
    private ReviseItemRequestItemTagsAttrSetAttr3SelectedValue selectedValueField;
    
    private string attrNameField;
    
    private string attrIDField;
    
    /// <remarks/>
    public ReviseItemRequestItemTagsAttrSetAttr3SelectedValue SelectedValue {
        get {
            return this.selectedValueField;
        }
        set {
            this.selectedValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AttrName {
        get {
            return this.attrNameField;
        }
        set {
            this.attrNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AttrID {
        get {
            return this.attrIDField;
        }
        set {
            this.attrIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemTagsAttrSetAttr3SelectedValue {
    
    private string valueNameField;
    
    private string valueIDField;
    
    private string otherValueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ValueName {
        get {
            return this.valueNameField;
        }
        set {
            this.valueNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ValueID {
        get {
            return this.valueIDField;
        }
        set {
            this.valueIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OtherValue {
        get {
            return this.otherValueField;
        }
        set {
            this.otherValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemTagsAttrSetAttr4 {
    
    private ReviseItemRequestItemTagsAttrSetAttr4SelectedValue selectedValueField;
    
    private string attrNameField;
    
    private string attrIDField;
    
    /// <remarks/>
    public ReviseItemRequestItemTagsAttrSetAttr4SelectedValue SelectedValue {
        get {
            return this.selectedValueField;
        }
        set {
            this.selectedValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AttrName {
        get {
            return this.attrNameField;
        }
        set {
            this.attrNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AttrID {
        get {
            return this.attrIDField;
        }
        set {
            this.attrIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemTagsAttrSetAttr4SelectedValue {
    
    private string valueNameField;
    
    private string valueIDField;
    
    private string otherValueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ValueName {
        get {
            return this.valueNameField;
        }
        set {
            this.valueNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ValueID {
        get {
            return this.valueIDField;
        }
        set {
            this.valueIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OtherValue {
        get {
            return this.otherValueField;
        }
        set {
            this.otherValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemTagsAttrSetAttr5 {
    
    private ReviseItemRequestItemTagsAttrSetAttr5SelectedValue selectedValueField;
    
    private string attrNameField;
    
    private string attrIDField;
    
    /// <remarks/>
    public ReviseItemRequestItemTagsAttrSetAttr5SelectedValue SelectedValue {
        get {
            return this.selectedValueField;
        }
        set {
            this.selectedValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AttrName {
        get {
            return this.attrNameField;
        }
        set {
            this.attrNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AttrID {
        get {
            return this.attrIDField;
        }
        set {
            this.attrIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemTagsAttrSetAttr5SelectedValue {
    
    private string valueNameField;
    
    private string valueIDField;
    
    private string otherValueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ValueName {
        get {
            return this.valueNameField;
        }
        set {
            this.valueNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ValueID {
        get {
            return this.valueIDField;
        }
        set {
            this.valueIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OtherValue {
        get {
            return this.otherValueField;
        }
        set {
            this.otherValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemTagsAttrSetAttr6 {
    
    private ReviseItemRequestItemTagsAttrSetAttr6SelectedValue selectedValueField;
    
    private string attrNameField;
    
    private string attrIDField;
    
    /// <remarks/>
    public ReviseItemRequestItemTagsAttrSetAttr6SelectedValue SelectedValue {
        get {
            return this.selectedValueField;
        }
        set {
            this.selectedValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AttrName {
        get {
            return this.attrNameField;
        }
        set {
            this.attrNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AttrID {
        get {
            return this.attrIDField;
        }
        set {
            this.attrIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemTagsAttrSetAttr6SelectedValue {
    
    private string valueNameField;
    
    private string valueIDField;
    
    private string otherValueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ValueName {
        get {
            return this.valueNameField;
        }
        set {
            this.valueNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ValueID {
        get {
            return this.valueIDField;
        }
        set {
            this.valueIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OtherValue {
        get {
            return this.otherValueField;
        }
        set {
            this.otherValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemTagsAttrSetAttr7 {
    
    private ReviseItemRequestItemTagsAttrSetAttr7SelectedValue selectedValueField;
    
    private string attrNameField;
    
    private string attrIDField;
    
    /// <remarks/>
    public ReviseItemRequestItemTagsAttrSetAttr7SelectedValue SelectedValue {
        get {
            return this.selectedValueField;
        }
        set {
            this.selectedValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AttrName {
        get {
            return this.attrNameField;
        }
        set {
            this.attrNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AttrID {
        get {
            return this.attrIDField;
        }
        set {
            this.attrIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemTagsAttrSetAttr7SelectedValue {
    
    private string valueNameField;
    
    private string valueIDField;
    
    private string otherValueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ValueName {
        get {
            return this.valueNameField;
        }
        set {
            this.valueNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ValueID {
        get {
            return this.valueIDField;
        }
        set {
            this.valueIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OtherValue {
        get {
            return this.otherValueField;
        }
        set {
            this.otherValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemTagsAttrSetAttr8 {
    
    private ReviseItemRequestItemTagsAttrSetAttr8SelectedValue selectedValueField;
    
    private string attrNameField;
    
    private string attrIDField;
    
    /// <remarks/>
    public ReviseItemRequestItemTagsAttrSetAttr8SelectedValue SelectedValue {
        get {
            return this.selectedValueField;
        }
        set {
            this.selectedValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AttrName {
        get {
            return this.attrNameField;
        }
        set {
            this.attrNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AttrID {
        get {
            return this.attrIDField;
        }
        set {
            this.attrIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemTagsAttrSetAttr8SelectedValue {
    
    private string valueNameField;
    
    private string valueIDField;
    
    private string otherValueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ValueName {
        get {
            return this.valueNameField;
        }
        set {
            this.valueNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ValueID {
        get {
            return this.valueIDField;
        }
        set {
            this.valueIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OtherValue {
        get {
            return this.otherValueField;
        }
        set {
            this.otherValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemTagsAttrSetAttr9 {
    
    private ReviseItemRequestItemTagsAttrSetAttr9SelectedValue selectedValueField;
    
    private string attrNameField;
    
    private string attrIDField;
    
    /// <remarks/>
    public ReviseItemRequestItemTagsAttrSetAttr9SelectedValue SelectedValue {
        get {
            return this.selectedValueField;
        }
        set {
            this.selectedValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AttrName {
        get {
            return this.attrNameField;
        }
        set {
            this.attrNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AttrID {
        get {
            return this.attrIDField;
        }
        set {
            this.attrIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemTagsAttrSetAttr9SelectedValue {
    
    private string valueNameField;
    
    private string valueIDField;
    
    private string otherValueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ValueName {
        get {
            return this.valueNameField;
        }
        set {
            this.valueNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ValueID {
        get {
            return this.valueIDField;
        }
        set {
            this.valueIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OtherValue {
        get {
            return this.otherValueField;
        }
        set {
            this.otherValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemTagsAttrSetAttr10 {
    
    private ReviseItemRequestItemTagsAttrSetAttr10SelectedValue selectedValueField;
    
    private string attrNameField;
    
    private string attrIDField;
    
    /// <remarks/>
    public ReviseItemRequestItemTagsAttrSetAttr10SelectedValue SelectedValue {
        get {
            return this.selectedValueField;
        }
        set {
            this.selectedValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AttrName {
        get {
            return this.attrNameField;
        }
        set {
            this.attrNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AttrID {
        get {
            return this.attrIDField;
        }
        set {
            this.attrIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemTagsAttrSetAttr10SelectedValue {
    
    private string valueNameField;
    
    private string valueIDField;
    
    private string otherValueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ValueName {
        get {
            return this.valueNameField;
        }
        set {
            this.valueNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ValueID {
        get {
            return this.valueIDField;
        }
        set {
            this.valueIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OtherValue {
        get {
            return this.otherValueField;
        }
        set {
            this.otherValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemPromotionalFeatures {
    
    private string highlightListingField;
    
    private string frontpageField;
    
    private string categorySpecialField;
    
    private string boldField;
    
    private string bidNowField;
    
    private string auto1MinuteField;
    
    /// <remarks/>
    public string HighlightListing {
        get {
            return this.highlightListingField;
        }
        set {
            this.highlightListingField = value;
        }
    }
    
    /// <remarks/>
    public string Frontpage {
        get {
            return this.frontpageField;
        }
        set {
            this.frontpageField = value;
        }
    }
    
    /// <remarks/>
    public string CategorySpecial {
        get {
            return this.categorySpecialField;
        }
        set {
            this.categorySpecialField = value;
        }
    }
    
    /// <remarks/>
    public string Bold {
        get {
            return this.boldField;
        }
        set {
            this.boldField = value;
        }
    }
    
    /// <remarks/>
    public string BidNow {
        get {
            return this.bidNowField;
        }
        set {
            this.bidNowField = value;
        }
    }
    
    /// <remarks/>
    public string Auto1Minute {
        get {
            return this.auto1MinuteField;
        }
        set {
            this.auto1MinuteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemAutoRelistFeatures {
    
    private string autoRelistTypeField;
    
    /// <remarks/>
    public string AutoRelistType {
        get {
            return this.autoRelistTypeField;
        }
        set {
            this.autoRelistTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemPaymentMethods {
    
    private string bankChequeField;
    
    private string bankDepositField;
    
    private string cashField;
    
    private object cODField;
    
    private string creditCardField;
    
    private string escrowField;
    
    private string moneyOrderField;
    
    private string paymateField;
    
    private string payPalField;
    
    private string personalChequeField;
    
    private string otherField;
    
    private string provideBankDetailsToBuyerField;
    
    /// <remarks/>
    public string BankCheque {
        get {
            return this.bankChequeField;
        }
        set {
            this.bankChequeField = value;
        }
    }
    
    /// <remarks/>
    public string BankDeposit {
        get {
            return this.bankDepositField;
        }
        set {
            this.bankDepositField = value;
        }
    }
    
    /// <remarks/>
    public string Cash {
        get {
            return this.cashField;
        }
        set {
            this.cashField = value;
        }
    }
    
    /// <remarks/>
    public object COD {
        get {
            return this.cODField;
        }
        set {
            this.cODField = value;
        }
    }
    
    /// <remarks/>
    public string CreditCard {
        get {
            return this.creditCardField;
        }
        set {
            this.creditCardField = value;
        }
    }
    
    /// <remarks/>
    public string Escrow {
        get {
            return this.escrowField;
        }
        set {
            this.escrowField = value;
        }
    }
    
    /// <remarks/>
    public string MoneyOrder {
        get {
            return this.moneyOrderField;
        }
        set {
            this.moneyOrderField = value;
        }
    }
    
    /// <remarks/>
    public string Paymate {
        get {
            return this.paymateField;
        }
        set {
            this.paymateField = value;
        }
    }
    
    /// <remarks/>
    public string PayPal {
        get {
            return this.payPalField;
        }
        set {
            this.payPalField = value;
        }
    }
    
    /// <remarks/>
    public string PersonalCheque {
        get {
            return this.personalChequeField;
        }
        set {
            this.personalChequeField = value;
        }
    }
    
    /// <remarks/>
    public string Other {
        get {
            return this.otherField;
        }
        set {
            this.otherField = value;
        }
    }
    
    /// <remarks/>
    public string ProvideBankDetailsToBuyer {
        get {
            return this.provideBankDetailsToBuyerField;
        }
        set {
            this.provideBankDetailsToBuyerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemPostage {
    
    private string typeField;
    
    private string fixedPostageField;
    
    private ReviseItemRequestItemPostageFixedPostageByLocation fixedPostageByLocationField;
    
    private ReviseItemRequestItemPostageCalculatedPostage calculatedPostageField;
    
    private ReviseItemRequestItemPostageTemando temandoField;
    
    /// <remarks/>
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string FixedPostage {
        get {
            return this.fixedPostageField;
        }
        set {
            this.fixedPostageField = value;
        }
    }
    
    /// <remarks/>
    public ReviseItemRequestItemPostageFixedPostageByLocation FixedPostageByLocation {
        get {
            return this.fixedPostageByLocationField;
        }
        set {
            this.fixedPostageByLocationField = value;
        }
    }
    
    /// <remarks/>
    public ReviseItemRequestItemPostageCalculatedPostage CalculatedPostage {
        get {
            return this.calculatedPostageField;
        }
        set {
            this.calculatedPostageField = value;
        }
    }
    
    /// <remarks/>
    public ReviseItemRequestItemPostageTemando Temando {
        get {
            return this.temandoField;
        }
        set {
            this.temandoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemPostageFixedPostageByLocation {
    
    private string nSWField;
    
    private string vICField;
    
    private string qLDField;
    
    private string aCTField;
    
    private string ntField;
    
    private string tASField;
    
    private string saField;
    
    private string waField;
    
    /// <remarks/>
    public string NSW {
        get {
            return this.nSWField;
        }
        set {
            this.nSWField = value;
        }
    }
    
    /// <remarks/>
    public string VIC {
        get {
            return this.vICField;
        }
        set {
            this.vICField = value;
        }
    }
    
    /// <remarks/>
    public string QLD {
        get {
            return this.qLDField;
        }
        set {
            this.qLDField = value;
        }
    }
    
    /// <remarks/>
    public string ACT {
        get {
            return this.aCTField;
        }
        set {
            this.aCTField = value;
        }
    }
    
    /// <remarks/>
    public string NT {
        get {
            return this.ntField;
        }
        set {
            this.ntField = value;
        }
    }
    
    /// <remarks/>
    public string TAS {
        get {
            return this.tASField;
        }
        set {
            this.tASField = value;
        }
    }
    
    /// <remarks/>
    public string SA {
        get {
            return this.saField;
        }
        set {
            this.saField = value;
        }
    }
    
    /// <remarks/>
    public string WA {
        get {
            return this.waField;
        }
        set {
            this.waField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemPostageCalculatedPostage {
    
    private ReviseItemRequestItemPostageCalculatedPostageDimensions dimensionsField;
    
    private string offerAPRegularField;
    
    private string offerAPExpressField;
    
    /// <remarks/>
    public ReviseItemRequestItemPostageCalculatedPostageDimensions Dimensions {
        get {
            return this.dimensionsField;
        }
        set {
            this.dimensionsField = value;
        }
    }
    
    /// <remarks/>
    public string OfferAPRegular {
        get {
            return this.offerAPRegularField;
        }
        set {
            this.offerAPRegularField = value;
        }
    }
    
    /// <remarks/>
    public string OfferAPExpress {
        get {
            return this.offerAPExpressField;
        }
        set {
            this.offerAPExpressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemPostageCalculatedPostageDimensions {
    
    private string lengthField;
    
    private string widthField;
    
    private string heightField;
    
    private string weightField;
    
    /// <remarks/>
    public string Length {
        get {
            return this.lengthField;
        }
        set {
            this.lengthField = value;
        }
    }
    
    /// <remarks/>
    public string Width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    public string Height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    public string Weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemPostageTemando {
    
    private string pkgTypeField;
    
    private string weightField;
    
    private string lengthField;
    
    private string widthField;
    
    private string heightField;
    
    /// <remarks/>
    public string PkgType {
        get {
            return this.pkgTypeField;
        }
        set {
            this.pkgTypeField = value;
        }
    }
    
    /// <remarks/>
    public string Weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
    
    /// <remarks/>
    public string Length {
        get {
            return this.lengthField;
        }
        set {
            this.lengthField = value;
        }
    }
    
    /// <remarks/>
    public string Width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    public string Height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReviseItemRequestItemPostToLocation {
    
    private string worldwideField;
    
    private string nationalField;
    
    private string statewideField;
    
    private string localPickupField;
    
    /// <remarks/>
    public string Worldwide {
        get {
            return this.worldwideField;
        }
        set {
            this.worldwideField = value;
        }
    }
    
    /// <remarks/>
    public string National {
        get {
            return this.nationalField;
        }
        set {
            this.nationalField = value;
        }
    }
    
    /// <remarks/>
    public string Statewide {
        get {
            return this.statewideField;
        }
        set {
            this.statewideField = value;
        }
    }
    
    /// <remarks/>
    public string LocalPickup {
        get {
            return this.localPickupField;
        }
        set {
            this.localPickupField = value;
        }
    }
}
